---
driver:
  name: ec2
  region: <%= ENV['AWS_REGION'] %>
  subnet_id: <%= ENV['SUBNET_ID'] %>
  security_group_ids: ["<%= ENV['SG_ID'] %>"]
  aws_ssh_key_id: <%= ENV['SSH_KEY'] %>
  iam_profile_name: <%= ENV['IAM_PROFILE'] %>
  associate_public_ip: <%= ENV['PUBLIC_IP'] %>
  tags:
    Name: "role-base"
    Owner: <%= ENV['TAGS_OWNER'] %>
    ExpirationDate: <%= ENV['TAGS_EXPIRY'] %>
    Environment: <%= ENV['TAGS_ENVIRONMENT'] %>
    Product: <%= ENV['TAGS_PRODUCT'] %>
    Project: <%= ENV['TAGS_PROJECT'] %>

transport:
  name: speedy_ssh
  ssh_key: <%= ENV['SSH_KEY_PATH'] %>

verifier:
  name: inspec

platforms:
  - name: rhel6
    driver:
      instance_type: t2.large
      image_id: <%= ENV['AWS_RHEL_6_AMI'] %>
      user_data: ./.user_data.sh
    transport:
      username: ec2-user
  - name: rhel7
    driver:
      instance_type: t2.large
      image_id: <%= ENV['AWS_RHEL_7_AMI'] %>
    transport:
      username: ec2-user
  - name: centos7
    driver:
      instance_type: t2.large
      image_id: <%= ENV['AWS_CENTOS_7_AMI'] %>
      user_data: ./.user_data.sh
    transport:
      username: centos
  - name: amazonlinux
    driver:
      instance_type: t2.large
      image_id: <%= ENV['AWS_AMAZONLINUX_AMI'] %>
      user_data: ./.user_data.sh
    transport:
      username: ec2-user
  - name: ubuntu14
    driver:
      instance_type: t2.large
      image_id: <%= ENV['AWS_UBUNTU_14_AMI'] %>
    transport:
      username: ubuntu
  - name: ubuntu16
    driver:
      instance_type: t2.large
      image_id: <%= ENV['AWS_UBUNTU_16_AMI'] %>
    transport:
      username: ubuntu

suites:
  - name: role-base
    verifier:
      inspec_tests:
        - test/integration/default
    run_list:
      - recipe[role-base]
    attributes:

