language: ruby
sudo: false
rvm:
- 2.1.8
before_install:
- gem update bundler
notifications:
  email:
    on_success: never
    on_failure:
    - andyboutte@gmail.com
env:
  global:
  - secure: sez/vCAm9aUFVPe/b8qY4M1aISDBV1QVPmMqfzzMNgcAW1KmbBpUtY7u3NgR4pxYh8pmUbxynk3+JdSQ8y3O+AfTNC2VTLTOEQAOTZNm9m8aL4PlnEskc7mppLbzLj7tL79rJOiBO0GVIrx0yNdYJNk7A4PcZ7gPpDBQxOdzytcFMOpYlsIYDhuB97fCts286B6CGjisVuhtC/U3hhJxKyYdV5VjNavMpHB/5NfpjeRrbbBsFv2PQHDpzfl56dEhYyX4WE7a1CjWagwHF10XAWb+yBceVZp4V7vtElZ3CKI4p+88tffP6RkBQzdp7KYeVlxgvencbzl5wOYUoqvEQ0Xlpnl0Xu7D/0tJd54nPbm70YUhmMNx960anmKfmgQaFwgkwZVD9WnjgRZc40mUDEg2mAUh6FEEfRLUdR6+oljqSbGrxmQxd4UIlePB+nOMrCwmnVhFW1UA+eUew6sEoJtIvz+jryRerqLCNZf0qbS0yioAjxxkVoLGIxYhjNxt6VufR+TqMULL5Ee5SdHPurR48fqKlYXXMGOMT40tX6X64J4BkFb3ubqtKkPPGwaJ0xP5BWifItOaJnRNjUJ/8SSH1KhvRZCrcrPd6A/5WOyld+2nyqCAbIytbt9YkXPKG1gIhdZTPkiP5xcQQh9FfoHekSsAanKWA5cPg75nUzw=
  - secure: P7iAF9iidi8BFtlHem75yPl0qN/prc4HX0h88JdurU4Epn5m2x+BhdwoJQ2hzXutbY3EaZhcqIbtLFBUphexJTNLc7CAKTXCIo83a7/6JQSLZ6ZlyfnwYQTER0Mb37Ivh10DsyN0D3homKBxze7phF+BN2VCeM/RcbXaaqmQ7SFH9HpaJUZgCY8qhInFwI+DHGx/UtHXVeQ48fAv4FCPjUB7ULnstMO8SgeNlMr9PmzbNcD2IBsGPz0T7o5OEtmaS9oK33Qw/MYS9zE0ad64Sw+ycf0N46C7V6TyobKJcG0/NxCEax3gDkEX1chIle61rrLts6aGogjLVgvxwxzEbxjvaJCtTwUBRiD3FlR/Ui4/qn2sQf89wYZyMubKn1YjGUizmL5nKNFyD/CYmfUkGfULRCYDhWQl3cXTfceyTmUO200+bMY1csm2ZEewXZ3OSgVl2WeIg6c42dDKMZvYLFJ26k5c3wzMkhrVn6wT/1jAEpF6erYJZcn9WYFBAHiLTfnsVGgNlVUsSjIFtrhyWJPJeEyEYuojc8kuVQ591UBnkRl6kgSPJI4zzGGErczwjuHsVKDAPEk2ex7s3tlNUMj5Ymc4fMVwqdbAbxo5v/1vYv+WgBRGt1WHfjhDa6QHCk/QBY35XThdtIEsEyu1zU7qDbNiD0twd/EnFDp8Rak=
