sudo: required
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: andyboutte@gmail.com

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: bundle install

services: docker

env:
  matrix:
  - INSTANCE=centos-6
  - INSTANCE=centos-7
  - INSTANCE=ubuntu-1404
  - INSTANCE=ubuntu-1604

before_script:
  - chef --version
  - cookstyle --version
  - foodcritic --version
  - docker -v

script: KITCHEN_LOCAL_YAML=.kitchen.local.yml kitchen verify ${INSTANCE}